apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain-explorer.fullname" . }}
  labels:
    {{- include "blockchain-explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.securePort }}
      targetPort: https
      protocol: TCP
      name: https   
  selector:
    {{- include "blockchain-explorer.selectorLabels" . | nindent 4 }}
