## 310-geth-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-explorer-config
  labels:
    app: blockchain-explorer-config
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  upstream_logging  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout 75;

      gzip  on;

      ###################################
      ## Microservices root URLs
      ## !!! upstream name MUST be equal to the service subdomain name

      upstream explorer-backend {
        # server explorer-backend.main.svc.cluster.local;
        server explorer-backend.ndau.tech:443;
      }

      server {
        listen       80;
        server_name  localhost;
        access_log /dev/stdout upstream_logging;
        resolver 1.1.1.1;

        proxy_set_header Host explorer-backend.ndau.tech;

        client_max_body_size 64M;
        
        ##################################
        ## API forwarding rules

        location ~* /([a-z]+)/api/(.+)$ {
          proxy_pass https://explorer-backend/api/$2$is_args$args;
        }

        location ~* ^/api/ {
          proxy_pass https://explorer-backend;
        }

        ## End of API forwarding rules
        ####################################

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }

        # redirect server error pages to the static page /50x.html
        # error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
